# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'
        cache: true

    - name: Vet
      run: go vet .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'
        cache: true

    - name: Build
      run: cd web && GOOS=linux GOARCH=amd64 go build -o krip_demo

    - name: Copy and run
      uses: mdallasanta/ssh-scp-deploy@v1.2.0
      with:
        local: './web/krip_demo'
        remote: '~/krip'
        host: ${{secrets.DEPLOY_HOST}}
        user: ${{secrets.DEPLOY_USERNAME}}
        key: ${{secrets.DEPLOY_PRIVATE_KEY}}
        pre_upload: systemctl stop krip --user
        post_upload: systemctl start krip --user
        ssh_options: -o StrictHostKeyChecking=no
